version: '3.7'

services:
  # client:
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5400:5400
  #   networks:
  #     - mern-network
  #   volumes:
  #     - ./client/src:/usr/app/src
  #     - ./client/public:/usr/app/public
  #   depends_on:
  #     - server
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   command: npm start
  #   stdin_open: true
  #   tty: true
  helpdesk:
    image: helpdesk
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/usr/app/src
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mern-network
  mongo:
    container_name: mongodb-container-name
    restart: always
    # use specific mongo verion in production
    image: mongo:latest
    command: mongod --noauth
    volumes:
      - ./imsdb:/data/db
    ports:  
      - "27017:27017"
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
