version: '3.4'

services:
  helpdesk:
    image: helpdesk
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3006:3006
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
